# Generated by Django 6.0.3 on 2026-03-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gate_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SecurityZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("hr_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(max_length=100)),
                (
                    "access_rights",
                    models.ManyToManyField(
                        blank=True,
                        related_name="employees",
                        to="card_person_check.accessright",
                    ),
                ),
                (
                    "current_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="card_person_check.securityzone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("card_id", models.CharField(max_length=50, unique=True)),
                (
                    "card_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("related_hr_id", models.CharField(editable=False, max_length=50)),
                ("lock_until", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_cards",
                        to="card_person_check.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GateEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("control", models.BooleanField(default=False, editable=False)),
                ("allowed", models.BooleanField(default=False, editable=False)),
                (
                    "warning",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card_person_check.card",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card_person_check.gate",
                    ),
                ),
                (
                    "from_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_from_zone",
                        to="card_person_check.securityzone",
                    ),
                ),
                (
                    "to_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_to_zone",
                        to="card_person_check.securityzone",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gate",
            name="inside_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gates_inside",
                to="card_person_check.securityzone",
            ),
        ),
        migrations.AddField(
            model_name="gate",
            name="outside_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gates_outside",
                to="card_person_check.securityzone",
            ),
        ),
        migrations.AddField(
            model_name="accessright",
            name="security_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="card_person_check.securityzone",
            ),
        ),
    ]
