# Generated by Django 6.0.3 on 2026-03-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("hr_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("card_id", models.CharField(max_length=50, unique=True)),
                (
                    "card_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("related_hr_id", models.CharField(editable=False, max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_cards",
                        to="card_person_check.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GateEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gate", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("control", models.BooleanField(default=False)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card_person_check.card",
                    ),
                ),
            ],
        ),
    ]
