# Generated by Django 6.0.3 on 2026-03-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hr_id",
            field=models.IntegerField(unique=True),
        ),
    ]
