# Generated by Django 6.0.3 on 2026-03-29 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrightrequest",
            name="supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_right_requests_for_supervisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
