# Generated by Django 6.0.3 on 2026-03-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0002_alter_gateevent_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="lock_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
