# Generated by Django 6.0.3 on 2026-03-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0002_accessright_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="access_rights",
        ),
    ]
