# Generated by Django 6.0.3 on 2026-03-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0003_card_lock_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateevent",
            name="allowed",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
