# Generated by Django 6.0.3 on 2026-03-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0003_remove_employee_access_rights"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRightRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("approved", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_right_requests_for_employee",
                        to="card_person_check.employee",
                    ),
                ),
                (
                    "security_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card_person_check.securityzone",
                    ),
                ),
            ],
        ),
    ]
