# Generated by Django 6.0.3 on 2026-03-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0004_gateevent_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateevent",
            name="warning",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="gateevent",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="card_person_check.card",
            ),
        ),
    ]
