# Generated by Django 6.0.3 on 2026-03-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0005_gateevent_warning_alter_gateevent_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateevent",
            name="warning",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
