# Generated by Django 6.0.3 on 2026-03-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0006_alter_gateevent_warning"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="cards",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="card_person_check.card"
            ),
        ),
    ]
