# Generated by Django 6.0.3 on 2026-03-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0007_securityzone_employee_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gate_number", models.IntegerField()),
                (
                    "inside_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates_inside",
                        to="card_person_check.securityzone",
                    ),
                ),
                (
                    "outside_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates_outside",
                        to="card_person_check.securityzone",
                    ),
                ),
            ],
        ),
    ]
