# Generated by Django 6.0.3 on 2026-03-24 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0008_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateevent",
            name="from_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_from_zone",
                to="card_person_check.securityzone",
            ),
        ),
        migrations.AddField(
            model_name="gateevent",
            name="to_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_to_zone",
                to="card_person_check.securityzone",
            ),
        ),
    ]
