# Generated by Django 6.0.3 on 2026-03-24 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0009_gateevent_from_zone_gateevent_to_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateevent",
            name="gate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="card_person_check.gate",
            ),
        ),
    ]
