# Generated by Django 6.0.3 on 2026-03-25 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0010_alter_gateevent_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="current_zone",
            field=models.ForeignKey(
                blank=True,
                default="Outside",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="card_person_check.securityzone",
            ),
        ),
        migrations.CreateModel(
            name="AccessRight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "security_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card_person_check.securityzone",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="access_rights",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="card_person_check.accessright"
            ),
        ),
    ]
