# Generated by Django 6.0.3 on 2026-03-25 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0011_employee_current_zone_accessright_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="current_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="card_person_check.securityzone",
            ),
        ),
    ]
