# Generated by Django 6.0.3 on 2026-03-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("card_person_check", "0012_alter_employee_current_zone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="cards",
        ),
    ]
